### PR TITLE
GAMS divide immediate wrong order

### LINKED ISSUE #74: NaN or inf found in linear terms
On model kport from the GAMS model library, I get plenty of this in the SHOT log:
```
     1: LP           0.02                      -1e+12 | -1e+12          inf. | inf.    
        Hyperplane for constraint SPP(L10)_rf  not generated,  NaN or inf found in linear terms for f(R1,L10) = 0.400000
        Hyperplane for constraint SPP(L10)_rf  not generated,  NaN or inf found in linear terms for f(R2,L10) = 0.400000
        Hyperplane for constraint SPP(L10)_rf  not generated,  NaN or inf found in linear terms for vR(R1) = 102.140000
        Hyperplane for constraint SPP(L10)_rf  not generated,  NaN or inf found in linear terms for vR(R2) = 176.070000
        Hyperplane for constraint SPP(L10)_rf  not generated,  NaN or inf found in linear terms for nB(R1,L10) = 0.000000
        Hyperplane for constraint SPP(L10)_rf  not generated,  NaN or inf found in linear terms for nB(R2,L10) = 0.000000
```
and eventually
```
 Terminated since no additional dual cuts can be added.

 No solution found. Try modifying the termination criteria.
```

### PR DESCRIPTION
**Pull request by andreaslundell**
This should fix #74. The problem was that the divide immediate instruction was inverted.

### CODE REVIEW

**Comment by svigerske** [comment]
That sounds serious. Then nlDivV seems to be also wrong.
If I read [some other code](https://github.com/coin-or/GAMSlinks/blob/master/src/scip/reader_gmo.c#L723) correctly, then
- `nlDiv` should be `rbegin()[1] / rbegin()[0]`. That's what I also see in SHOT.
- `nlDivV` should be `rbegin()[0] / var`
- `nlDivI` should be `rbegin()[0] / constant`

**Comment by andreaslundell** [comment]
I'll go through them and make sure they are right. Strange that this has not caused problems before...

**Comment by andreaslundell** [comment]
So now it should be okay. I guess since I mostly test SHOT and GAMS on the MINLPLib instances, convert changes the divide immediate to a multiplication. And perhaps the nlDivV is never present there as well. I have compared GAMS vs NL vs OSiL on the instances there with same results, so I am quite certain there are no problems reading the instances (or I do the same mistake in all of them :) )...

**Comment by svigerske** [comment]
Division is overrated anyway. :)

**Pull request merged**
