### PR TITLE
Issue49

### LINKED ISSUE #49: debug facility when not running from problem file
Two things.

I do not set `Input.ProblemFile` in my use of the SHOT library. This makes the code in `Solver::initializeDebugMode()` that tries to copy the problem file into the debug dir fail:
```
       fs::filesystem::path source(
          fs::filesystem::canonical(env->settings->getSetting<std::string>("ProblemFile", "Input")));

       fs::filesystem::copy_file(
          source.string(), (debugDir / source.filename()).string(), fs::filesystem::copy_options::overwrite_existing);
```
Can one do this only if Input.ProblemFile has been set? Or give a warning if the input file is not found an continue?

In `bool Solver::setProblem(SHOT::ProblemPtr problem, SHOT::ModelingSystemPtr modelingSystem)`, the debug path that I can set via option Debug.Path is overwritten:
```
    if(static_cast<ES_OutputDirectory>(env->settings->getSetting<int>("OutputDirectory", "Output"))
        == ES_OutputDirectory::Program)
    {
        fs::filesystem::path debugPath(fs::filesystem::current_path());
        debugPath /= problem->name;

        env->settings->updateSetting("Debug.Path", "Output", debugPath.string());
        env->settings->updateSetting("ResultPath", "Output", fs::filesystem::current_path().string());
    }
```
If I already have a regular file with name `problem->name` in my directory, then the debug facitility will just fail, I guess. If I already have a directory with name `problem->name` in my directory, files in there may be overwritten.

It would be good if SHOT would not just overwrite my setting and maybe also choose a more unique name for the debug output directory than `problem->name` by default. Maybe add something like ".shot.debug" as suffix?

### PR DESCRIPTION
**Pull request by andreaslundell**
This should fix #49. But I guess the "correct" way to do this on GAMS would to create some specific subfolder in the GAMS temporary directory? In this case you could just set `Output.Debug.Path` to be that directory.

### CODE REVIEW

**Comment by andreaslundell** [comment]
If you have SHOT built on Windows, it would be great if you could try if creating a temporary directory does work...

**Comment by svigerske** [comment]
You didn't like something as in `ModelingSystemGAMS::createModelFromProblemFile()` ? Too much C-like?

**Comment by andreaslundell** [comment]
I was not aware, and `#if _DEFAULT_SOURCE || _BSD_SOURCE || _POSIX_C_SOURCE >= 200809L` really makes me feel a little bit uncomfortable :D

**Comment by andreaslundell** [comment]
Should I modify it in `ModelingSystemGAMS` as well? Can we really assume that the runtime directory (or the directory the user currently is) is writable?

**Comment by svigerske** [comment]
That is the feature check I got from `man mkdtemp`.
Fine with me if you want to change that.

I merged this, so I can get everything together. It looked ok, too.
I'll have a look into setting a different default Debug.Path from EntryPointsGAMS and try the debug option on Windows.

**Comment by svigerske** [comment]
I did some more fixes for this on master.

**Comment by svigerske** [comment]
> If you have SHOT built on Windows, it would be great if you could try if creating a temporary directory does work...

Looks like it works. :+1: 

I get
```
 Debug directory:            C:\Users\***\AppData\Local\Temp\2\SHOT_debug_42992a3cb2821c3
```
and there are a number of files ending up in that dir.

**Pull request merged**
